version: "3"

services:
  simply-pay-php:
    image: php:8.2-fpm
    build:
      context: ./
      dockerfile: ./build/docker/Dockerfile
    container_name: simply-pay-php
    restart: unless-stopped
    volumes:
      - .:/var/www:cached
    networks:
      - simply_pay_net

  simply-pay-db:
    image: mysql/mysql-server:8.0.23
    container_name: simply-pay-db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - "simply_pay_data:/var/lib/mysql:cached"
    ports:
      - "${DB_PORT}:3306"
    networks:
      - simply_pay_net

  simply-pay-nginx:
    image: nginx:alpine
    container_name: simply-pay-nginx
    restart: unless-stopped
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - .:/var/www:cached
      - ./build/nginx:/etc/nginx/conf.d/:cached
    networks:
      - simply_pay_net

volumes:
  simply_pay_data:

networks:
  simply_pay_net:
